#!/usr/bin/env node

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const [sourceDirectory, outputFile] = process.argv.slice(2);
if (!sourceDirectory || !outputFile) {
  throw new Error("Usage: generate_strength_catalog.mjs <exercises directory> <output file>");
}

// Nombres revisados con terminología habitual de gimnasio en español. No se
// construyen mediante sustituciones de palabras: eso producía frases poco
// naturales y, peor aún, podía cambiar el sentido técnico del ejercicio.
const reviewedSpanishNames = new Map([
  ["3_4_Sit-Up", "Abdominal de tres cuartos"],
  ["Ab_Crunch_Machine", "Máquina de abdominales"],
  ["Ab_Roller", "Rueda abdominal"],
  ["Advanced_Kettlebell_Windmill", "Molino avanzado con kettlebell"],
  ["Air_Bike", "Bicicleta de aire"],
  ["Alternate_Hammer_Curl", "Curl martillo alterno"],
  ["Alternate_Heel_Touchers", "Toques alternos de talón"],
  ["Alternate_Incline_Dumbbell_Curl", "Curl alterno inclinado con mancuernas"],
  ["Alternating_Cable_Shoulder_Press", "Press de hombros alterno en polea"],
  ["Alternating_Deltoid_Raise", "Elevación de hombros alterna"],
  ["Alternating_Floor_Press", "Press de suelo alterno"],
  ["Alternating_Hang_Clean", "Cargada colgante alterna"],
  ["Alternating_Kettlebell_Press", "Press alterno con kettlebell"],
  ["Alternating_Kettlebell_Row", "Remo alterno con kettlebell"],
  ["Alternating_Renegade_Row", "Remo renegado alterno"],
  ["Anti-Gravity_Press", "Press antigravedad"],
  ["Arnold_Dumbbell_Press", "Press Arnold con mancuernas"],
  ["Around_The_Worlds", "Vuelta al mundo con mancuernas"],
  ["Back_Flyes_-_With_Bands", "Aperturas inversas con bandas"],
  ["Balance_Board", "Tabla de equilibrio"],
  ["Ball_Leg_Curl", "Curl femoral con fitball"],
  ["Band_Assisted_Pull-Up", "Dominadas asistidas con banda"],
  ["Band_Hip_Adductions", "Aducción de cadera con banda"],
  ["Band_Pull_Apart", "Apertura de banda"],
  ["Band_Skull_Crusher", "Rompecráneos con banda"],
  ["Barbell_Ab_Rollout", "Desplazamiento abdominal con barra"],
  ["Barbell_Ab_Rollout_-_On_Knees", "Desplazamiento abdominal de rodillas con barra"],
  ["Barbell_Bench_Press_-_Medium_Grip", "Press de banca con barra (agarre medio)"],
  ["Barbell_Curl", "Curl de bíceps con barra"],
  ["Barbell_Curls_Lying_Against_An_Incline", "Curl con barra tumbado en banco inclinado"],
  ["Barbell_Deadlift", "Peso muerto con barra"],
  ["Barbell_Full_Squat", "Sentadilla profunda con barra"],
  ["Barbell_Guillotine_Bench_Press", "Press guillotina con barra"],
  ["Barbell_Hack_Squat", "Sentadilla hack con barra"],
  ["Barbell_Incline_Bench_Press_-_Medium_Grip", "Press inclinado con barra (agarre medio)"],
  ["Barbell_Incline_Shoulder_Raise", "Elevación de hombros inclinada con barra"],
  ["Barbell_Lunge", "Zancada con barra"],
  ["Barbell_Rear_Delt_Row", "Remo con barra para deltoides posterior"],
  ["Barbell_Rollout_from_Bench", "Desplazamiento con barra desde banco"],
  ["Barbell_Seated_Calf_Raise", "Elevación de gemelos sentado con barra"],
  ["Barbell_Shoulder_Press", "Press de hombros con barra"],
  ["Barbell_Shrug", "Encogimiento con barra"],
  ["Barbell_Shrug_Behind_The_Back", "Encogimiento con barra tras la espalda"],
  ["Barbell_Side_Bend", "Inclinación lateral con barra"],
  ["Barbell_Side_Split_Squat", "Zancada lateral con barra"],
  ["Barbell_Squat", "Sentadilla con barra"],
  ["Barbell_Squat_To_A_Bench", "Sentadilla con barra a banco"],
  ["Barbell_Step_Ups", "Subidas al banco con barra"],
  ["Barbell_Walking_Lunge", "Zancadas caminando con barra"],
  ["Battling_Ropes", "Cuerdas de batalla"],
  ["Bench_Dips", "Fondos en banco"],
  ["Bench_Press_-_With_Bands", "Press de banca con bandas"],
  ["Bent_Over_Barbell_Row", "Remo inclinado con barra"],
  ["Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench", "Elevación posterior inclinado con mancuerna y apoyo en banco"],
  ["Bent_Over_Low-Pulley_Side_Lateral", "Elevación lateral inclinado en polea baja"],
  ["Bent_Over_One-Arm_Long_Bar_Row", "Remo inclinado unilateral con barra larga"],
  ["Bent_Over_Two-Arm_Long_Bar_Row", "Remo inclinado bilateral con barra larga"],
  ["Bent_Over_Two-Dumbbell_Row", "Remo inclinado con dos mancuernas"],
  ["Bent_Over_Two-Dumbbell_Row_With_Palms_In", "Remo inclinado con dos mancuernas y agarre neutro"],
  ["Bent_Press", "Press inclinado lateral"],
  ["Bent-Arm_Barbell_Pullover", "Pullover con barra y brazos flexionados"],
  ["Bent-Arm_Dumbbell_Pullover", "Pullover con mancuerna y brazos flexionados"],
  ["Bent-Knee_Hip_Raise", "Elevación de cadera con rodillas flexionadas"],
  ["Body_Tricep_Press", "Fondos de tríceps con peso corporal"],
  ["Body-Up", "Body-up"],
  ["Bodyweight_Flyes", "Aperturas con peso corporal"],
  ["Bodyweight_Mid_Row", "Remo medio con peso corporal"],
  ["Bodyweight_Squat", "Sentadilla con peso corporal"],
  ["Bodyweight_Walking_Lunge", "Zancadas caminando con peso corporal"],
  ["Bosu_Ball_Cable_Crunch_With_Side_Bends", "Crunch en polea sobre bosu con inclinación lateral"],
  ["Bottoms_Up", "Levantamiento de piernas desde tumbado"],
  ["Bottoms-Up_Clean_From_The_Hang_Position", "Cargada colgante bottoms-up"],
  ["Box_Squat_with_Chains", "Sentadilla a caja con cadenas"],
  ["Bradford_Rocky_Presses", "Press Bradford"],
  ["Butt_Lift_Bridge", "Puente de glúteos"],
  ["Butt-Ups", "Elevación de glúteos"],
  ["Butterfly", "Mariposa en máquina"],
  ["Cable_Chest_Press", "Press de pecho en polea"],
  ["Cable_Crossover", "Cruce de poleas"],
  ["Cable_Crunch", "Crunch en polea"],
  ["Cable_Deadlifts", "Peso muerto en polea"],
  ["Cable_Hammer_Curls_-_Rope_Attachment", "Curl martillo en polea con cuerda"],
  ["Cable_Hip_Adduction", "Aducción de cadera en polea"],
  ["Cable_Incline_Pushdown", "Extensión de tríceps inclinada en polea"],
  ["Cable_Incline_Triceps_Extension", "Extensión de tríceps inclinada en polea"],
  ["Cable_Internal_Rotation", "Rotación interna en polea"],
  ["Cable_Iron_Cross", "Cruce de hierro en polea"],
  ["Cable_Judo_Flip", "Giro de judo en polea"],
  ["Cable_Lying_Triceps_Extension", "Extensión de tríceps tumbado en polea"],
  ["Cable_One_Arm_Tricep_Extension", "Extensión unilateral de tríceps en polea"],
  ["Cable_Preacher_Curl", "Curl predicador en polea"],
  ["Cable_Rear_Delt_Fly", "Aperturas posteriores en polea"],
  ["Cable_Reverse_Crunch", "Crunch inverso en polea"],
  ["Cable_Rope_Overhead_Triceps_Extension", "Extensión de tríceps por encima de la cabeza con cuerda"],
  ["Cable_Rope_Rear-Delt_Rows", "Remo posterior con cuerda en polea"],
  ["Cable_Russian_Twists", "Giros rusos en polea"],
  ["Cable_Seated_Crunch", "Crunch sentado en polea"],
  ["Cable_Seated_Lateral_Raise", "Elevación lateral sentado en polea"],
  ["Cable_Shoulder_Press", "Press de hombros en polea"],
  ["Cable_Shrugs", "Encogimientos en polea"],
  ["Cable_Wrist_Curl", "Curl de muñeca en polea"],
  ["Calf_Press", "Prensa de gemelos"],
  ["Calf_Press_On_The_Leg_Press_Machine", "Prensa de gemelos en prensa de piernas"],
  ["Calf_Raise_On_A_Dumbbell", "Elevación de gemelos sobre mancuerna"],
  ["Calf_Raises_-_With_Bands", "Elevación de gemelos con bandas"],
  ["Calf-Machine_Shoulder_Shrug", "Encogimiento en máquina de gemelos"],
  ["Car_Drivers", "Volantes con disco"],
  ["Chair_Squat", "Sentadilla a silla"],
  ["Chin-Up", "Dominada supina"],
  ["Clean_and_Press", "Cargada y press"],
  ["Clock_Push-Up", "Flexión de reloj"],
  ["Close-Grip_Barbell_Bench_Press", "Press de banca con barra y agarre cerrado"],
  ["Close-Grip_Dumbbell_Press", "Press con mancuernas y agarre cerrado"],
  ["Close-Grip_EZ_Bar_Curl", "Curl con barra EZ y agarre cerrado"],
  ["Close-Grip_EZ-Bar_Curl_with_Band", "Curl con barra EZ y banda, agarre cerrado"],
  ["Close-Grip_EZ-Bar_Press", "Press con barra EZ y agarre cerrado"],
  ["Close-Grip_Front_Lat_Pulldown", "Jalón frontal con agarre cerrado"],
  ["Close-Grip_Push-Up_off_of_a_Dumbbell", "Flexión con agarre cerrado sobre mancuernas"],
  ["Close-Grip_Standing_Barbell_Curl", "Curl de pie con barra y agarre cerrado"],
  ["Cocoons", "Abdominales en ovillo"],
  ["Concentration_Curls", "Curl de concentración"],
  ["Cross_Body_Hammer_Curl", "Curl martillo cruzado"],
  ["Cross_Over_-_With_Bands", "Cruce con bandas"],
  ["Cross-Body_Crunch", "Crunch cruzado"],
  ["Crunch_-_Hands_Overhead", "Crunch con brazos por encima de la cabeza"],
  ["Crunch_-_Legs_On_Exercise_Ball", "Crunch con piernas en fitball"],
  ["Crunches", "Crunch abdominal"],
  ["Cuban_Press", "Press cubano"],
  ["Dead_Bug", "Dead bug"],
  ["Decline_Barbell_Bench_Press", "Press declinado con barra"],
  ["Decline_Close-Grip_Bench_To_Skull_Crusher", "Press declinado cerrado a rompecráneos"],
  ["Decline_Crunch", "Crunch declinado"],
  ["Decline_Dumbbell_Bench_Press", "Press declinado con mancuernas"],
  ["Decline_Dumbbell_Flyes", "Aperturas declinadas con mancuernas"],
  ["Decline_Dumbbell_Triceps_Extension", "Extensión de tríceps declinada con mancuernas"],
  ["Decline_EZ_Bar_Triceps_Extension", "Extensión de tríceps declinada con barra EZ"],
  ["Decline_Oblique_Crunch", "Crunch oblicuo declinado"],
  ["Decline_Push-Up", "Flexión declinada"],
  ["Decline_Reverse_Crunch", "Crunch inverso declinado"],
  ["Decline_Smith_Press", "Press declinado en multipower"],
  ["Dip_Machine", "Máquina de fondos"],
  ["Dips_-_Chest_Version", "Fondos para pecho"],
  ["Dips_-_Triceps_Version", "Fondos para tríceps"],
  ["Donkey_Calf_Raises", "Elevación de gemelos a burro"],
  ["Double_Kettlebell_Alternating_Hang_Clean", "Cargada colgante alterna con dos kettlebells"],
  ["Double_Kettlebell_Jerk", "Envión con dos kettlebells"],
  ["Double_Kettlebell_Push_Press", "Push press con dos kettlebells"],
  ["Double_Kettlebell_Snatch", "Arrancada con dos kettlebells"],
  ["Double_Kettlebell_Windmill", "Molino con dos kettlebells"],
  ["Downward_Facing_Balance", "Equilibrio en posición invertida"],
  ["Drag_Curl", "Curl arrastre"],
  ["Dumbbell_Alternate_Bicep_Curl", "Curl de bíceps alterno con mancuernas"],
  ["Dumbbell_Bench_Press", "Press de banca con mancuernas"],
  ["Dumbbell_Bench_Press_with_Neutral_Grip", "Press de banca con mancuernas y agarre neutro"],
  ["Dumbbell_Bicep_Curl", "Curl de bíceps con mancuernas"],
  ["Dumbbell_Clean", "Cargada con mancuernas"],
  ["Dumbbell_Flyes", "Aperturas con mancuernas"],
  ["Dumbbell_Incline_Row", "Remo inclinado con mancuernas"],
  ["Dumbbell_Incline_Shoulder_Raise", "Elevación de hombros inclinada con mancuernas"],
  ["Dumbbell_Lunges", "Zancadas con mancuernas"],
  ["Dumbbell_Lying_One-Arm_Rear_Lateral_Raise", "Elevación lateral posterior unilateral tumbado con mancuerna"],
  ["Dumbbell_Lying_Pronation", "Pronación tumbado con mancuerna"],
  ["Dumbbell_Lying_Rear_Lateral_Raise", "Elevación lateral posterior tumbado con mancuernas"],
  ["Dumbbell_Lying_Supination", "Supinación tumbado con mancuerna"],
  ["Dumbbell_One-Arm_Shoulder_Press", "Press de hombros unilateral con mancuerna"],
  ["Dumbbell_One-Arm_Triceps_Extension", "Extensión unilateral de tríceps con mancuerna"],
  ["Dumbbell_One-Arm_Upright_Row", "Remo al mentón unilateral con mancuerna"],
  ["Dumbbell_Prone_Incline_Curl", "Curl inclinado boca abajo con mancuernas"],
  ["Dumbbell_Raise", "Elevación con mancuernas"],
  ["Dumbbell_Rear_Lunge", "Zancada hacia atrás con mancuernas"],
  ["Dumbbell_Scaption", "Scaption con mancuernas"],
  ["Dumbbell_Seated_One-Leg_Calf_Raise", "Elevación de gemelos unilateral sentado con mancuerna"],
  ["Dumbbell_Shoulder_Press", "Press de hombros con mancuernas"],
  ["Dumbbell_Shrug", "Encogimiento con mancuernas"],
  ["Dumbbell_Side_Bend", "Inclinación lateral con mancuerna"],
  ["Dumbbell_Squat", "Sentadilla con mancuernas"],
  ["Dumbbell_Squat_To_A_Bench", "Sentadilla con mancuernas a banco"],
  ["Dumbbell_Step_Ups", "Subidas al banco con mancuernas"],
  ["Dumbbell_Tricep_Extension_-Pronated_Grip", "Extensión de tríceps con mancuerna y agarre prono"],
  ["Elbow_to_Knee", "Codo a rodilla"],
  ["Elevated_Back_Lunge", "Zancada trasera elevada"],
  ["Elevated_Cable_Rows", "Remo elevado en polea"],
  ["Exercise_Ball_Crunch", "Crunch en fitball"],
  ["Exercise_Ball_Pull-In", "Encogimiento de piernas en fitball"],
  ["Extended_Range_One-Arm_Kettlebell_Floor_Press", "Press de suelo unilateral con kettlebell y rango ampliado"],
  ["External_Rotation", "Rotación externa"],
  ["External_Rotation_with_Band", "Rotación externa con banda"],
  ["External_Rotation_with_Cable", "Rotación externa en polea"],
  ["EZ-Bar_Curl", "Curl con barra EZ"],
  ["EZ-Bar_Skullcrusher", "Rompecráneos con barra EZ"],
  ["Face_Pull", "Face pull"],
  ["Finger_Curls", "Curl de dedos"],
  ["Flat_Bench_Cable_Flyes", "Aperturas en polea con banco plano"],
  ["Flat_Bench_Leg_Pull-In", "Encogimiento de piernas en banco plano"],
  ["Flat_Bench_Lying_Leg_Raise", "Elevación de piernas tumbado en banco plano"],
  ["Flexor_Incline_Dumbbell_Curls", "Curl de antebrazos inclinado con mancuernas"],
  ["Floor_Glute-Ham_Raise", "Elevación de glúteo e isquios en suelo"],
  ["Flutter_Kicks", "Patadas de tijera"],
  ["Freehand_Jump_Squat", "Sentadilla con salto"],
  ["Frog_Sit-Ups", "Abdominales rana"],
  ["Front_Barbell_Squat", "Sentadilla frontal con barra"],
  ["Front_Barbell_Squat_To_A_Bench", "Sentadilla frontal con barra a banco"],
  ["Front_Cable_Raise", "Elevación frontal en polea"],
  ["Front_Dumbbell_Raise", "Elevación frontal con mancuernas"],
  ["Front_Incline_Dumbbell_Raise", "Elevación frontal inclinada con mancuernas"],
  ["Front_Plate_Raise", "Elevación frontal con disco"],
  ["Front_Raise_And_Pullover", "Elevación frontal y pullover"],
  ["Front_Squat_Clean_Grip", "Sentadilla frontal con agarre de cargada"],
  ["Front_Squats_With_Two_Kettlebells", "Sentadilla frontal con dos kettlebells"],
  ["Front_Two-Dumbbell_Raise", "Elevación frontal con dos mancuernas"],
  ["Full_Range-Of-Motion_Lat_Pulldown", "Jalón al pecho con recorrido completo"],
  ["Gironda_Sternum_Chins", "Dominadas al esternón de Gironda"],
  ["Glute_Kickback", "Patada de glúteo"],
  ["Goblet_Squat", "Sentadilla copa"],
  ["Gorilla_Chin_Crunch", "Crunch gorila"],
  ["Hack_Squat", "Sentadilla hack"],
  ["Hammer_Curls", "Curl martillo"],
  ["Hammer_Grip_Incline_DB_Bench_Press", "Press inclinado con mancuernas y agarre neutro"],
  ["Handstand_Push-Ups", "Flexiones en pino"],
  ["Hanging_Leg_Raise", "Elevación de piernas colgado"],
  ["Hanging_Pike", "Pike colgado"],
  ["High_Cable_Curls", "Curl en polea alta"],
  ["Hip_Extension_with_Bands", "Extensión de cadera con bandas"],
  ["Hip_Flexion_with_Band", "Flexión de cadera con banda"],
  ["Hyperextensions_Back_Extensions", "Hiperextensiones lumbares"],
  ["Hyperextensions_With_No_Hyperextension_Bench", "Hiperextensiones en suelo"],
  ["Incline_Barbell_Triceps_Extension", "Extensión de tríceps inclinada con barra"],
  ["Incline_Bench_Pull", "Remo en banco inclinado"],
  ["Incline_Cable_Chest_Press", "Press de pecho inclinado en polea"],
  ["Incline_Cable_Flye", "Apertura inclinada en polea"],
  ["Incline_Dumbbell_Bench_With_Palms_Facing_In", "Press inclinado con mancuernas y agarre neutro"],
  ["Incline_Dumbbell_Curl", "Curl inclinado con mancuernas"],
  ["Incline_Dumbbell_Flyes", "Aperturas inclinadas con mancuernas"],
  ["Incline_Dumbbell_Flyes_-_With_A_Twist", "Aperturas inclinadas con giro"],
  ["Incline_Dumbbell_Press", "Press inclinado con mancuernas"],
  ["Incline_Hammer_Curls", "Curl martillo inclinado"],
  ["Incline_Inner_Biceps_Curl", "Curl inclinado de bíceps interno"],
  ["Incline_Push-Up", "Flexión inclinada"],
  ["Incline_Push-Up_Close-Grip", "Flexión inclinada con agarre cerrado"],
  ["Incline_Push-Up_Medium", "Flexión inclinada con agarre medio"],
  ["Incline_Push-Up_Reverse_Grip", "Flexión inclinada con agarre inverso"],
  ["Incline_Push-Up_Wide", "Flexión inclinada con agarre amplio"],
  ["Internal_Rotation_with_Band", "Rotación interna con banda"],
  ["Inverted_Row", "Remo invertido"],
  ["Inverted_Row_with_Straps", "Remo invertido con correas"],
  ["Iron_Cross", "Cruce de hierro"],
  ["Isometric_Neck_Exercise_-_Front_And_Back", "Isométrico de cuello frontal y posterior"],
  ["Isometric_Neck_Exercise_-_Sides", "Isométrico lateral de cuello"],
  ["Isometric_Wipers", "Limpiaparabrisas isométrico"],
  ["Jackknife_Sit-Up", "Abdominal navaja"],
  ["Janda_Sit-Up", "Abdominal Janda"],
  ["Jefferson_Squats", "Sentadilla Jefferson"],
  ["JM_Press", "Press JM"],
  ["Kettlebell_Arnold_Press", "Press Arnold con kettlebell"],
  ["Kettlebell_Dead_Clean", "Cargada desde el suelo con kettlebell"],
  ["Kettlebell_Figure_8", "Figura ocho con kettlebell"],
  ["Kettlebell_Hang_Clean", "Cargada colgante con kettlebell"],
  ["Kettlebell_One-Legged_Deadlift", "Peso muerto unilateral con kettlebell"],
  ["Kettlebell_Pass_Between_The_Legs", "Pase de kettlebell entre las piernas"],
  ["Kettlebell_Pirate_Ships", "Barco pirata con kettlebell"],
  ["Kettlebell_Pistol_Squat", "Sentadilla pistol con kettlebell"],
  ["Kettlebell_Seated_Press", "Press sentado con kettlebell"],
  ["Kettlebell_Seesaw_Press", "Press balancín con kettlebell"],
  ["Kettlebell_Sumo_High_Pull", "Tirón alto sumo con kettlebell"],
  ["Kettlebell_Thruster", "Thruster con kettlebell"],
  ["Kettlebell_Turkish_Get-Up_Lunge_style", "Levantamiento turco con kettlebell (zancada)"],
  ["Kettlebell_Turkish_Get-Up_Squat_style", "Levantamiento turco con kettlebell (sentadilla)"],
  ["Kettlebell_Windmill", "Molino con kettlebell"],
  ["Kipping_Muscle_Up", "Muscle-up con kipping"],
  ["Knee_Hip_Raise_On_Parallel_Bars", "Elevación de rodillas y cadera en paralelas"],
  ["Kneeling_Cable_Crunch_With_Alternating_Oblique_Twists", "Crunch de rodillas en polea con giro oblicuo alterno"],
  ["Kneeling_Cable_Triceps_Extension", "Extensión de tríceps de rodillas en polea"],
  ["Kneeling_High_Pulley_Row", "Remo de rodillas en polea alta"],
  ["Kneeling_Single-Arm_High_Pulley_Row", "Remo unilateral de rodillas en polea alta"],
  ["Landmine_180s", "Landmine 180º"],
  ["Landmine_Linear_Jammer", "Press lineal landmine"],
  ["Lateral_Raise_-_With_Bands", "Elevación lateral con bandas"],
  ["Leg_Extensions", "Extensión de piernas en máquina"],
  ["Leg_Lift", "Elevación de piernas"],
  ["Leg_Press", "Prensa de piernas"],
  ["Leg_Pull-In", "Encogimiento de piernas"],
  ["Leg-Over_Floor_Press", "Press de suelo con piernas elevadas"],
  ["Leverage_Chest_Press", "Press de pecho en máquina"],
  ["Leverage_Deadlift", "Peso muerto en máquina"],
  ["Leverage_Decline_Chest_Press", "Press de pecho declinado en máquina"],
  ["Leverage_High_Row", "Remo alto en máquina"],
  ["Leverage_Incline_Chest_Press", "Press de pecho inclinado en máquina"],
  ["Leverage_Iso_Row", "Remo iso-lateral en máquina"],
  ["Leverage_Shoulder_Press", "Press de hombros en máquina"],
  ["Leverage_Shrug", "Encogimiento en máquina"],
  ["London_Bridges", "Puentes London"],
  ["Low_Cable_Crossover", "Cruce de poleas bajo"],
  ["Low_Cable_Triceps_Extension", "Extensión de tríceps en polea baja"],
  ["Low_Pulley_Row_To_Neck", "Remo a cuello en polea baja"],
  ["Lunge_Pass_Through", "Zancada con pase"],
  ["Lunge_Sprint", "Zancada de sprint"],
  ["Lying_Cable_Curl", "Curl tumbado en polea"],
  ["Lying_Cambered_Barbell_Row", "Remo tumbado con barra curvada"],
  ["Lying_Close-Grip_Bar_Curl_On_High_Pulley", "Curl tumbado con barra en polea alta y agarre cerrado"],
  ["Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head", "Extensión de tríceps tumbado con barra tras la cabeza"],
  ["Lying_Close-Grip_Barbell_Triceps_Press_To_Chin", "Press de tríceps tumbado con barra al mentón"],
  ["Lying_Dumbbell_Tricep_Extension", "Extensión de tríceps tumbado con mancuernas"],
  ["Lying_Face_Down_Plate_Neck_Resistance", "Resistencia de cuello boca abajo con disco"],
  ["Lying_Face_Up_Plate_Neck_Resistance", "Resistencia de cuello boca arriba con disco"],
  ["Lying_High_Bench_Barbell_Curl", "Curl tumbado con barra en banco alto"],
  ["Lying_Leg_Curls", "Curl femoral tumbado"],
  ["Lying_Machine_Squat", "Sentadilla tumbado en máquina"],
  ["Lying_One-Arm_Lateral_Raise", "Elevación lateral unilateral tumbado"],
  ["Lying_Rear_Delt_Raise", "Elevación posterior tumbado"],
  ["Lying_Supine_Dumbbell_Curl", "Curl supino tumbado con mancuernas"],
  ["Lying_T-Bar_Row", "Remo T tumbado"],
  ["Lying_Triceps_Press", "Press de tríceps tumbado"],
  ["Machine_Bench_Press", "Press de banca en máquina"],
  ["Machine_Bicep_Curl", "Curl de bíceps en máquina"],
  ["Machine_Preacher_Curls", "Curl predicador en máquina"],
  ["Machine_Shoulder_Military_Press", "Press militar de hombros en máquina"],
  ["Machine_Triceps_Extension", "Extensión de tríceps en máquina"],
  ["Middle_Back_Shrug", "Encogimiento para espalda media"],
  ["Mixed_Grip_Chin", "Dominada con agarre mixto"],
  ["Monster_Walk", "Caminata monstruo"],
  ["Muscle_Up", "Muscle-up"],
  ["Narrow_Stance_Hack_Squats", "Sentadilla hack con postura estrecha"],
  ["Narrow_Stance_Leg_Press", "Prensa de piernas con postura estrecha"],
  ["Narrow_Stance_Squats", "Sentadilla con postura estrecha"],
  ["Natural_Glute_Ham_Raise", "Elevación natural de glúteo e isquios"],
  ["Neck_Press", "Press al cuello"],
  ["Oblique_Crunches", "Crunch oblicuo"],
  ["Oblique_Crunches_-_On_The_Floor", "Crunch oblicuo en suelo"],
  ["One_Arm_Chin-Up", "Dominada supina a un brazo"],
  ["One_Arm_Dumbbell_Bench_Press", "Press de banca unilateral con mancuerna"],
  ["One_Arm_Dumbbell_Preacher_Curl", "Curl predicador unilateral con mancuerna"],
  ["One_Arm_Floor_Press", "Press de suelo unilateral"],
  ["One_Arm_Lat_Pulldown", "Jalón al pecho unilateral"],
  ["One_Arm_Pronated_Dumbbell_Triceps_Extension", "Extensión unilateral de tríceps con mancuerna y agarre prono"],
  ["One_Arm_Supinated_Dumbbell_Triceps_Extension", "Extensión unilateral de tríceps con mancuerna y agarre supino"],
  ["One_Leg_Barbell_Squat", "Sentadilla unilateral con barra"],
  ["One-Arm_Dumbbell_Row", "Remo unilateral con mancuerna"],
  ["One-Arm_Flat_Bench_Dumbbell_Flye", "Apertura unilateral con mancuerna en banco plano"],
  ["One-Arm_High-Pulley_Cable_Side_Bends", "Inclinación lateral unilateral en polea alta"],
  ["One-Arm_Incline_Lateral_Raise", "Elevación lateral unilateral inclinada"],
  ["One-Arm_Kettlebell_Clean", "Cargada unilateral con kettlebell"],
  ["One-Arm_Kettlebell_Clean_and_Jerk", "Cargada y envión unilateral con kettlebell"],
  ["One-Arm_Kettlebell_Floor_Press", "Press de suelo unilateral con kettlebell"],
  ["One-Arm_Kettlebell_Jerk", "Envión unilateral con kettlebell"],
  ["One-Arm_Kettlebell_Military_Press_To_The_Side", "Press militar lateral unilateral con kettlebell"],
  ["One-Arm_Kettlebell_Para_Press", "Press para unilateral con kettlebell"],
  ["One-Arm_Kettlebell_Push_Press", "Push press unilateral con kettlebell"],
  ["One-Arm_Kettlebell_Row", "Remo unilateral con kettlebell"],
  ["One-Arm_Kettlebell_Snatch", "Arrancada unilateral con kettlebell"],
  ["One-Arm_Kettlebell_Split_Jerk", "Envión en tijera unilateral con kettlebell"],
  ["One-Arm_Kettlebell_Split_Snatch", "Arrancada en tijera unilateral con kettlebell"],
  ["One-Arm_Kettlebell_Swings", "Balanceo unilateral con kettlebell"],
  ["One-Arm_Long_Bar_Row", "Remo unilateral con barra larga"],
  ["One-Arm_Medicine_Ball_Slam", "Golpe al suelo unilateral con balón medicinal"],
  ["One-Arm_Open_Palm_Kettlebell_Clean", "Cargada unilateral con kettlebell en palma abierta"],
  ["One-Arm_Overhead_Kettlebell_Squats", "Sentadilla unilateral con kettlebell sobre la cabeza"],
  ["One-Arm_Side_Deadlift", "Peso muerto lateral unilateral"],
  ["One-Arm_Side_Laterals", "Elevación lateral unilateral"],
  ["One-Legged_Cable_Kickback", "Patada de glúteo unilateral en polea"],
  ["Open_Palm_Kettlebell_Clean", "Cargada con kettlebell en palma abierta"],
  ["Otis-Up", "Otis-up"],
  ["Overhead_Cable_Curl", "Curl en polea por encima de la cabeza"],
  ["Pallof_Press", "Press Pallof"],
  ["Pallof_Press_With_Rotation", "Press Pallof con rotación"],
  ["Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench", "Curl de muñeca prono con mancuerna en banco"],
  ["Palms-Down_Wrist_Curl_Over_A_Bench", "Curl de muñeca prono en banco"],
  ["Palms-Up_Barbell_Wrist_Curl_Over_A_Bench", "Curl de muñeca supino con barra en banco"],
  ["Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench", "Curl de muñeca supino con mancuerna en banco"],
  ["Parallel_Bar_Dip", "Fondos en paralelas"],
  ["Physioball_Hip_Bridge", "Puente de cadera en fitball"],
  ["Plank", "Plancha"],
  ["Plate_Pinch", "Pinza de discos"],
  ["Plate_Twist", "Giro con disco"],
  ["Platform_Hamstring_Slides", "Deslizamientos de isquios"],
  ["Plie_Dumbbell_Squat", "Sentadilla plié con mancuerna"],
  ["Plyo_Kettlebell_Pushups", "Flexiones pliométricas sobre kettlebells"],
  ["Power_Clean", "Cargada de potencia"],
  ["Power_Partials", "Repeticiones parciales de potencia"],
  ["Preacher_Curl", "Curl predicador"],
  ["Preacher_Hammer_Dumbbell_Curl", "Curl martillo predicador con mancuerna"],
  ["Press_Sit-Up", "Abdominal con press"],
  ["Prone_Manual_Hamstring", "Curl femoral manual boca abajo"],
  ["Pull_Through", "Pull-through en polea"],
  ["Pullups", "Dominadas"],
  ["Push_Up_to_Side_Plank", "Flexión a plancha lateral"],
  ["Push-Up_Wide", "Flexión con agarre amplio"],
  ["Push-Ups_-_Close_Triceps_Position", "Flexiones cerradas para tríceps"],
  ["Push-Ups_With_Feet_Elevated", "Flexiones con pies elevados"],
  ["Push-Ups_With_Feet_On_An_Exercise_Ball", "Flexiones con pies en fitball"],
  ["Pushups", "Flexiones"],
  ["Pushups_Close_and_Wide_Hand_Positions", "Flexiones con agarres cerrado y amplio"],
  ["Reverse_Barbell_Curl", "Curl inverso con barra"],
  ["Reverse_Barbell_Preacher_Curls", "Curl predicador inverso con barra"],
  ["Reverse_Cable_Curl", "Curl inverso en polea"],
  ["Reverse_Crunch", "Crunch inverso"],
  ["Reverse_Flyes", "Aperturas inversas"],
  ["Reverse_Flyes_With_External_Rotation", "Aperturas inversas con rotación externa"],
  ["Reverse_Grip_Bent-Over_Rows", "Remo inclinado con agarre inverso"],
  ["Reverse_Grip_Triceps_Pushdown", "Extensión de tríceps en polea con agarre inverso"],
  ["Reverse_Hyperextension", "Hiperextensión inversa"],
  ["Reverse_Machine_Flyes", "Aperturas inversas en máquina"],
  ["Reverse_Plate_Curls", "Curl inverso con disco"],
  ["Reverse_Triceps_Bench_Press", "Press de banca inverso para tríceps"],
  ["Ring_Dips", "Fondos en anillas"],
  ["Rocking_Standing_Calf_Raise", "Elevación de gemelos de pie con balanceo"],
  ["Rocky_Pull-Ups_Pulldowns", "Dominadas/jalones Rocky"],
  ["Romanian_Deadlift", "Peso muerto rumano"],
  ["Rope_Climb", "Subida de cuerda"],
  ["Rope_Crunch", "Crunch con cuerda"],
  ["Rope_Straight-Arm_Pulldown", "Jalón de brazos rectos con cuerda"],
  ["Russian_Twist", "Giro ruso"],
  ["Scapular_Pull-Up", "Dominada escapular"],
  ["Seated_Band_Hamstring_Curl", "Curl femoral sentado con banda"],
  ["Seated_Barbell_Military_Press", "Press militar sentado con barra"],
  ["Seated_Barbell_Twist", "Giro sentado con barra"],
  ["Seated_Bent-Over_One-Arm_Dumbbell_Triceps_Extension", "Extensión unilateral de tríceps inclinado y sentado con mancuerna"],
  ["Seated_Bent-Over_Rear_Delt_Raise", "Elevación posterior inclinado y sentado"],
  ["Seated_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension", "Extensión bilateral de tríceps inclinado y sentado con mancuernas"],
  ["Seated_Cable_Rows", "Remo sentado en polea"],
  ["Seated_Cable_Shoulder_Press", "Press de hombros sentado en polea"],
  ["Seated_Calf_Raise", "Elevación de gemelos sentado"],
  ["Seated_Close-Grip_Concentration_Barbell_Curl", "Curl de concentración sentado con barra y agarre cerrado"],
  ["Seated_Dumbbell_Curl", "Curl sentado con mancuernas"],
  ["Seated_Dumbbell_Inner_Biceps_Curl", "Curl sentado de bíceps interno con mancuernas"],
  ["Seated_Dumbbell_Palms-Down_Wrist_Curl", "Curl de muñeca prono sentado con mancuernas"],
  ["Seated_Dumbbell_Palms-Up_Wrist_Curl", "Curl de muñeca supino sentado con mancuernas"],
  ["Seated_Dumbbell_Press", "Press sentado con mancuernas"],
  ["Seated_Flat_Bench_Leg_Pull-In", "Encogimiento de piernas sentado en banco plano"],
  ["Seated_Head_Harness_Neck_Resistance", "Resistencia de cuello sentado con arnés"],
  ["Seated_Leg_Curl", "Curl femoral sentado"],
  ["Seated_Leg_Tucks", "Encogimiento de piernas sentado"],
  ["Seated_One-arm_Cable_Pulley_Rows", "Remo unilateral sentado en polea"],
  ["Seated_One-Arm_Dumbbell_Palms-Down_Wrist_Curl", "Curl de muñeca prono unilateral sentado con mancuerna"],
  ["Seated_One-Arm_Dumbbell_Palms-Up_Wrist_Curl", "Curl de muñeca supino unilateral sentado con mancuerna"],
  ["Seated_Palm-Up_Barbell_Wrist_Curl", "Curl de muñeca supino sentado con barra"],
  ["Seated_Palms-Down_Barbell_Wrist_Curl", "Curl de muñeca prono sentado con barra"],
  ["Seated_Side_Lateral_Raise", "Elevación lateral sentado"],
  ["Seated_Triceps_Press", "Press de tríceps sentado"],
  ["Seated_Two-Arm_Palms-Up_Low-Pulley_Wrist_Curl", "Curl de muñeca supino bilateral sentado en polea baja"],
  ["See-Saw_Press_Alternating_Side_Press", "Press balancín alterno"],
  ["Shotgun_Row", "Remo escopeta"],
  ["Shoulder_Press_-_With_Bands", "Press de hombros con bandas"],
  ["Side_Bridge", "Plancha lateral"],
  ["Side_Jackknife", "Navaja lateral"],
  ["Side_Lateral_Raise", "Elevación lateral"],
  ["Side_Laterals_to_Front_Raise", "Elevaciones laterales a frontal"],
  ["Side_To_Side_Chins", "Dominadas de lado a lado"],
  ["Single_Dumbbell_Raise", "Elevación con una mancuerna"],
  ["Single_Leg_Glute_Bridge", "Puente de glúteo unilateral"],
  ["Single-Arm_Cable_Crossover", "Cruce de polea unilateral"],
  ["Single-Arm_Linear_Jammer", "Press lineal unilateral landmine"],
  ["Single-Arm_Push-Up", "Flexión a una mano"],
  ["Single-Leg_High_Box_Squat", "Sentadilla unilateral a caja alta"],
  ["Single-Leg_Leg_Extension", "Extensión de pierna unilateral"],
  ["Sit-Up", "Abdominal completo"],
  ["Sled_Overhead_Backward_Walk", "Caminata hacia atrás con trineo sobre la cabeza"],
  ["Sled_Overhead_Triceps_Extension", "Extensión de tríceps sobre la cabeza con trineo"],
  ["Sled_Reverse_Flye", "Apertura inversa con trineo"],
  ["Sled_Row", "Remo con trineo"],
  ["Smith_Incline_Shoulder_Raise", "Elevación de hombros inclinada en multipower"],
  ["Smith_Machine_Behind_the_Back_Shrug", "Encogimiento tras la espalda en multipower"],
  ["Smith_Machine_Bench_Press", "Press de banca en multipower"],
  ["Smith_Machine_Bent_Over_Row", "Remo inclinado en multipower"],
  ["Smith_Machine_Calf_Raise", "Elevación de gemelos en multipower"],
  ["Smith_Machine_Close-Grip_Bench_Press", "Press de banca cerrado en multipower"],
  ["Smith_Machine_Decline_Press", "Press declinado en multipower"],
  ["Smith_Machine_Hang_Power_Clean", "Cargada de potencia colgante en multipower"],
  ["Smith_Machine_Hip_Raise", "Elevación de cadera en multipower"],
  ["Smith_Machine_Incline_Bench_Press", "Press inclinado en multipower"],
  ["Smith_Machine_Leg_Press", "Prensa de piernas en multipower"],
  ["Smith_Machine_One-Arm_Upright_Row", "Remo al mentón unilateral en multipower"],
  ["Smith_Machine_Overhead_Shoulder_Press", "Press de hombros sobre la cabeza en multipower"],
  ["Smith_Machine_Pistol_Squat", "Sentadilla pistol en multipower"],
  ["Smith_Machine_Reverse_Calf_Raises", "Elevación inversa de gemelos en multipower"],
  ["Smith_Machine_Squat", "Sentadilla en multipower"],
  ["Smith_Machine_Stiff-Legged_Deadlift", "Peso muerto con piernas rígidas en multipower"],
  ["Smith_Machine_Upright_Row", "Remo al mentón en multipower"],
  ["Smith_Single-Leg_Split_Squat", "Sentadilla búlgara unilateral en multipower"],
  ["Snatch_Pull", "Tirón de arrancada"],
  ["Speed_Band_Overhead_Triceps", "Extensión rápida de tríceps sobre la cabeza con banda"],
  ["Speed_Squats", "Sentadillas de velocidad"],
  ["Spell_Caster", "Spell caster"],
  ["Spider_Crawl", "Caminata de araña"],
  ["Spider_Curl", "Curl araña"],
  ["Split_Squat_with_Dumbbells", "Zancada estática con mancuernas"],
  ["Squat_Jerk", "Envión en sentadilla"],
  ["Squat_with_Plate_Movers", "Sentadilla con discos móviles"],
  ["Squats_-_With_Bands", "Sentadillas con bandas"],
  ["Standing_Alternating_Dumbbell_Press", "Press alterno de pie con mancuernas"],
  ["Standing_Barbell_Calf_Raise", "Elevación de gemelos de pie con barra"],
  ["Standing_Barbell_Press_Behind_Neck", "Press de pie tras nuca con barra"],
  ["Standing_Bent-Over_One-Arm_Dumbbell_Triceps_Extension", "Extensión unilateral de tríceps inclinado de pie con mancuerna"],
  ["Standing_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension", "Extensión bilateral de tríceps inclinado de pie con mancuernas"],
  ["Standing_Biceps_Cable_Curl", "Curl de bíceps de pie en polea"],
  ["Standing_Bradford_Press", "Press Bradford de pie"],
  ["Standing_Cable_Chest_Press", "Press de pecho de pie en polea"],
  ["Standing_Cable_Lift", "Elevación diagonal de pie en polea"],
  ["Standing_Cable_Wood_Chop", "Leñador de pie en polea"],
  ["Standing_Calf_Raises", "Elevación de gemelos de pie"],
  ["Standing_Concentration_Curl", "Curl de concentración de pie"],
  ["Standing_Dumbbell_Calf_Raise", "Elevación de gemelos de pie con mancuerna"],
  ["Standing_Dumbbell_Press", "Press de pie con mancuernas"],
  ["Standing_Dumbbell_Reverse_Curl", "Curl inverso de pie con mancuernas"],
  ["Standing_Dumbbell_Straight-Arm_Front_Delt_Raise_Above_Head", "Elevación frontal de pie con brazos rectos y mancuernas"],
  ["Standing_Dumbbell_Triceps_Extension", "Extensión de tríceps de pie con mancuerna"],
  ["Standing_Dumbbell_Upright_Row", "Remo al mentón de pie con mancuernas"],
  ["Standing_Front_Barbell_Raise_Over_Head", "Elevación frontal de pie con barra sobre la cabeza"],
  ["Standing_Inner-Biceps_Curl", "Curl de bíceps interno de pie"],
  ["Standing_Leg_Curl", "Curl femoral de pie"],
  ["Standing_Low-Pulley_Deltoid_Raise", "Elevación de deltoides de pie en polea baja"],
  ["Standing_Low-Pulley_One-Arm_Triceps_Extension", "Extensión unilateral de tríceps de pie en polea baja"],
  ["Standing_Military_Press", "Press militar de pie"],
  ["Standing_Olympic_Plate_Hand_Squeeze", "Agarre de disco olímpico de pie"],
  ["Standing_One-Arm_Cable_Curl", "Curl unilateral de pie en polea"],
  ["Standing_One-Arm_Dumbbell_Curl_Over_Incline_Bench", "Curl unilateral de pie con mancuerna sobre banco inclinado"],
  ["Standing_One-Arm_Dumbbell_Triceps_Extension", "Extensión unilateral de tríceps de pie con mancuerna"],
  ["Standing_Overhead_Barbell_Triceps_Extension", "Extensión de tríceps de pie sobre la cabeza con barra"],
  ["Standing_Palm-In_One-Arm_Dumbbell_Press", "Press unilateral de pie con mancuerna y agarre neutro"],
  ["Standing_Palms-In_Dumbbell_Press", "Press de pie con mancuernas y agarre neutro"],
  ["Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl", "Curl de muñeca supino de pie con barra tras la espalda"],
  ["Standing_Rope_Crunch", "Crunch de pie con cuerda"],
  ["Standing_Towel_Triceps_Extension", "Extensión de tríceps de pie con toalla"],
  ["Step-up_with_Knee_Raise", "Subida al banco con elevación de rodilla"],
  ["Stiff_Leg_Barbell_Good_Morning", "Buenos días con barra y piernas rígidas"],
  ["Stiff-Legged_Barbell_Deadlift", "Peso muerto con barra y piernas rígidas"],
  ["Stiff-Legged_Dumbbell_Deadlift", "Peso muerto con mancuernas y piernas rígidas"],
  ["Straight_Bar_Bench_Mid_Rows", "Remo medio en banco con barra recta"],
  ["Straight_Raises_on_Incline_Bench", "Elevaciones rectas en banco inclinado"],
  ["Straight-Arm_Dumbbell_Pullover", "Pullover con mancuerna y brazos rectos"],
  ["Straight-Arm_Pulldown", "Jalón de brazos rectos"],
  ["Suspended_Fallout", "Fallout suspendido"],
  ["Suspended_Push-Up", "Flexión suspendida"],
  ["Suspended_Reverse_Crunch", "Crunch inverso suspendido"],
  ["Suspended_Row", "Remo suspendido"],
  ["Suspended_Split_Squat", "Zancada estática suspendida"],
  ["Svend_Press", "Press Svend"],
  ["T-Bar_Row_with_Handle", "Remo T con agarre"],
  ["Tate_Press", "Press Tate"],
  ["Thigh_Abductor", "Máquina de abductores"],
  ["Thigh_Adductor", "Máquina de aductores"],
  ["Trap_Bar_Deadlift", "Peso muerto con barra hexagonal"],
  ["Tricep_Dumbbell_Kickback", "Patada de tríceps con mancuerna"],
  ["Triceps_Overhead_Extension_with_Rope", "Extensión de tríceps sobre la cabeza con cuerda"],
  ["Triceps_Pushdown", "Extensión de tríceps en polea"],
  ["Triceps_Pushdown_-_Rope_Attachment", "Extensión de tríceps en polea con cuerda"],
  ["Triceps_Pushdown_-_V-Bar_Attachment", "Extensión de tríceps en polea con barra V"],
  ["Tuck_Crunch", "Crunch agrupado"],
  ["Two-Arm_Dumbbell_Preacher_Curl", "Curl predicador con dos mancuernas"],
  ["Two-Arm_Kettlebell_Clean", "Cargada con dos kettlebells"],
  ["Two-Arm_Kettlebell_Jerk", "Envión con dos kettlebells"],
  ["Two-Arm_Kettlebell_Military_Press", "Press militar con dos kettlebells"],
  ["Two-Arm_Kettlebell_Row", "Remo con dos kettlebells"],
  ["Underhand_Cable_Pulldowns", "Jalón en polea con agarre supino"],
  ["Upright_Barbell_Row", "Remo al mentón con barra"],
  ["Upright_Cable_Row", "Remo al mentón en polea"],
  ["Upright_Row_-_With_Bands", "Remo al mentón con bandas"],
  ["V-Bar_Pulldown", "Jalón al pecho con barra V"],
  ["V-Bar_Pullup", "Dominada con agarre V"],
  ["Weighted_Ball_Hyperextension", "Hiperextensión con balón medicinal"],
  ["Weighted_Ball_Side_Bend", "Inclinación lateral con balón medicinal"],
  ["Weighted_Bench_Dip", "Fondos en banco con lastre"],
  ["Weighted_Crunches", "Crunch con lastre"],
  ["Weighted_Jump_Squat", "Sentadilla con salto y lastre"],
  ["Weighted_Pull_Ups", "Dominadas con lastre"],
  ["Weighted_Sissy_Squat", "Sentadilla sissy con lastre"],
  ["Weighted_Sit-Ups_-_With_Bands", "Abdominales con lastre y bandas"],
  ["Weighted_Squat", "Sentadilla con lastre"],
  ["Wide_Stance_Barbell_Squat", "Sentadilla con barra y postura amplia"],
  ["Wide-Grip_Barbell_Bench_Press", "Press de banca con barra y agarre amplio"],
  ["Wide-Grip_Decline_Barbell_Bench_Press", "Press declinado con barra y agarre amplio"],
  ["Wide-Grip_Decline_Barbell_Pullover", "Pullover declinado con barra y agarre amplio"],
  ["Wide-Grip_Lat_Pulldown", "Jalón al pecho con agarre amplio"],
  ["Wide-Grip_Pulldown_Behind_The_Neck", "Jalón tras nuca con agarre amplio"],
  ["Wide-Grip_Rear_Pull-Up", "Dominada tras nuca con agarre amplio"],
  ["Wide-Grip_Standing_Barbell_Curl", "Curl de pie con barra y agarre amplio"],
  ["Wind_Sprints", "Sprints"],
  ["Wrist_Roller", "Rodillo de muñeca"],
  ["Wrist_Rotations_with_Straight_Bar", "Rotaciones de muñeca con barra recta"],
  ["Zercher_Squats", "Sentadilla Zercher"],
  ["Zottman_Curl", "Curl Zottman"],
  ["Zottman_Preacher_Curl", "Curl Zottman predicador"],
]);

function spanishName(id, englishName) {
  // Algunos nombres propios (por ejemplo, Svend press) se usan en inglés
  // también en España. Para las entradas aún no revisadas es preferible
  // conservar ese nombre reconocido a generar una traducción defectuosa.
  return reviewedSpanishNames.get(id) ?? englishName;
}

const filenames = await readdir(sourceDirectory);
const records = [];
for (const filename of filenames) {
  if (!filename.endsWith(".json")) continue;
  const source = JSON.parse(await readFile(join(sourceDirectory, filename), "utf8"));
  if (source.category !== "strength") continue;
  records.push({
    id: source.id,
    name_en: source.name,
    name_es: spanishName(source.id, source.name),
    force: source.force ?? null,
    level: source.level ?? null,
    mechanic: source.mechanic ?? null,
    equipment: source.equipment ?? null,
    primary_muscles: source.primaryMuscles ?? [],
    secondary_muscles: source.secondaryMuscles ?? [],
    instructions_en: source.instructions ?? [],
    image_paths: source.images ?? [],
  });
}

records.sort((left, right) => left.name_en.localeCompare(right.name_en, "en"));
await mkdir(outputFile.slice(0, outputFile.lastIndexOf("/")), { recursive: true });
await writeFile(outputFile, `${JSON.stringify(records)}\n`);
console.log(`Wrote ${records.length} strength exercises to ${outputFile}`);
